# Generated by Django 2.2.28 on 2023-04-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alligator_dog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turtle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.BigIntegerField()),
            ],
        ),
    ]
